name: Build HMCLauncher

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x86
      - name: Build HMCLauncher
        run: msbuild /p:Configuration=Release /t:Rebuild .
      - name: Create checksum file
        run: Out-File -InputObject (Get-FileHash -Path .\Release\HMCLauncher.exe -Algorithm SHA256).Hash.ToLower() -FilePath .\Release\HMCLauncher.exe.sha256 -NoNewline
      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: HMCLauncher-${{ env.SHORT_SHA }}
          path: |
            Release/HMCLauncher.exe
            Release/HMCLauncher.exe.sha256
      - name: Create release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release/HMCLauncher.exe
            Release/HMCLauncher.exe.sha256
